### ISSUE TITLE
Fix my crummy bash skills

### ISSUE THREAD

**Issue by bderiso** [bderiso/pCleaner#2]
Fix common issues noted here: http://mywiki.wooledge.org/BashPitfalls#for_i_in_.24.28ls_.2A.mp3.29

Specially: 
- the main filename loop that feeds the audio processing
- variable checks that might return an empty word.

**Comment by finalcommand** [comment]
Team work make the dream work.

**Comment by bderiso** [comment]
https://github.com/bderiso/pCleaner/pull/4
